# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 19, 23, 25, 32, 792744), max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('staff_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 19, 23, 25, 32, 791677), max_length=255)),
                ('intime', models.CharField(max_length=255)),
                ('outtime', models.CharField(max_length=255)),
                ('to_whom', models.CharField(max_length=512)),
                ('purpose', models.CharField(max_length=512)),
            ],
        ),
    ]
