# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20160421_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 10, 45, 24, 58142), max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 10, 45, 24, 56599), max_length=255),
        ),
    ]
