# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20160422_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('organiser', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 11, 16, 34, 720063), max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 11, 16, 34, 718498), max_length=255),
        ),
    ]
