# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20160422_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 21, 9, 38, 332830), max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 21, 9, 38, 330916), max_length=255),
        ),
    ]
