# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20160422_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 22, 21, 16, 19, 800018))),
                ('file_name', models.FileField(default='', upload_to=b'')),
                ('uploader', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 21, 16, 19, 799119), max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 22, 21, 16, 19, 797972), max_length=255),
        ),
    ]
